config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Landing page
  get 'home/index'

  # User
  resource :user, only: %i[edit update]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get '/sign_up', to: 'clearance/users#new', as: 'sign_up'

  # Password reset
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]

  # Session
  resource :session, controller: 'sessions', only: [:create]
  get '/session', to: redirect('/sign_in')
  get '/sign_in', to: 'sessions#new', as: 'sign_in'
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'

  # Show and save note
  resource :note, only: %i[edit update]

  # Default route
  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# Base class for models
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# frozen_string_literal: true

# Note model
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  include Clearance::User
  has_one :note, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application controller
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include HttpAcceptLanguage::AutoLocale
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home controller
class HomeController < ApplicationController
  before_action :redirect_if_logged_in
  layout 'application'

  # GET home/index
  def index
    @title = t('.title')
  end

  private

  # Don't show homepage if the user is logged in
  def redirect_if_logged_in
    redirect_to edit_note_path if signed_in?
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

# Notes controller
class NotesController < ApplicationController
  before_action :require_login
  before_action :set_note
  before_action :set_client_locales
  layout 'application'

  # GET note/edit
  def edit
    @title = t('.title')

    return unless @note.nil?

    # Create a new note if none exists for the user
    current_user.create_note(text: "Hello, here's your note!")
    @note = current_user.note
  end

  # PATCH note
  def update
    raise unless @note.update(note_params)
  end

  private

  # Load note model into context
  def set_note
    @note = current_user.note
  end

  # Pass some i18n phrases to the client to be used in JavaScript
  def set_client_locales
    @client_locales = {
      'notes.edit.saved' => t('.saved'),
      'notes.edit.saving_error' => t('.saving_error'),
      'notes.edit.saving' => t('.saving'),
      'notes.edit.unsaved_changes' => t('.unsaved_changes')
    }
  end

  # Permitted parameters for update
  def note_params
    params.require(:note).permit(:text)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Sessions controller
class SessionsController < Clearance::SessionsController
  before_action :set_render_notifications, only: %i[new create]

  private

  # Render notifications locally
  def set_render_notifications
    @template_renders_notifications = true
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User controller
class UsersController < ApplicationController
  before_action :require_login, :set_user, :set_render_notifications
  before_action :validate_password_confirmation, only: :update
  layout 'fullscreen_panel'

  # GET user/edit
  def edit
    @title = t('.title')
  end

  # PATCH user/update
  def update
    params = user_params

    # Don't touch the password if the field is empty
    params.delete(:password) if params[:password].blank?

    if @user.update(params)
      flash[:success] = t('.success')
    else
      flash[:error] = t('.error')
    end

    redirect_to edit_user_path
  end

  private

  # Load user model into context
  def set_user
    @user = current_user
  end

  # Render notifications locally
  def set_render_notifications
    @template_renders_notifications = true
  end

  # Make sure that password and confirmation match
  def validate_password_confirmation
    password_params = params.require(:user).permit(:password,
                                                   :password_confirmation)

    # We're done if password and confirmation match
    return if password_params[:password] ==
              password_params[:password_confirmation]

    # Otherwise, cancel request and show an error message
    flash[:error] = t('.passwords_dont_match')
    redirect_to edit_user_path
  end

  # Permitted parameters for update
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: false

# Application helpers
module ApplicationHelper
  # Create a link that will have the 'active' class set if its url matches the
  # current page
  def navbar_link_to(body, url, html_options)
    html_options = {} if html_options.blank?
    html_options[:class] = {} if html_options[:class].blank?

    active_class_name = 'active'
    active_class_name.prepend(' ') if html_options[:class].is_a?(String)
    html_options[:class] << active_class_name if current_page?(url)

    link_to body, url, html_options
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Home helpers
module HomeHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

# Notes helpers
module NotesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Users helpers
module UsersHelper
end

app/views/home/index.html.erb
<div class="home__wrapper">
  <div class="home">
    <div class="home__left">
      <div>
        <h1 class="home__title"><%= t('.title') %></h1>
        <p class="home__description">
          <%= t('.description') %>
        </p>
        <p class="home__footer">
          <%= t('.credits_html',
            author: link_to('Andreas Philippi',
              'https://anphil.github.io',
              target: '_blank'),
            repository: link_to('GitHub',
              'https://github.com/anphil/skriva',
              target: '_blank'),
            license: link_to('MIT license',
              'https://github.com/anphil/skriva/blob/master/LICENSE.md',
              target: '_blank')) %>
        </p>
      </div>
    </div>
    <div class="home__right">
      <%= render partial: 'sessions/new', layout: 'layouts/panel' %>
    </div>
  </div>
</div>

app/views/layouts/_master.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>Skriva<% if defined? @title %> | <%= @title %><% end %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://rsms.me/inter/inter-ui.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>

    <% if @client_locales %>
      <script>
        window.locales = <%= raw @client_locales.to_json %>
      </script>
    <% end %>
  </head>

  <body>
    <%# Flash messages %>
    <% unless @template_renders_notifications %>
      <%= render partial: 'shared/notifications' %>
    <% end %>

    <!-- Content -->
    <%= yield %>
  </body>
</html>

app/views/layouts/_panel.html.erb
<div class="panel">
  <%# Panel headline %>
  <% if content_for?(:header) %>
    <div class="panel__header">
      <div class="panel__title"><%= content_for :header %></div>
    </div>
  <% end %>

  <%# Navigation %>
  <% if content_for?(:navigation) %>
    <div class="panel__nav">
      <%= content_for :navigation %>
    </div>
  <% end %>

  <%# Content %>
  <% if content_for?(:body) %>
    <div class="panel__body">
      <%= content_for :body %>
    </div>
  <% end %>

  <%# Footer %>
  <% if content_for?(:footer) %>
    <div class="panel__footer">
      <%= content_for :footer %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<%= render layout: 'layouts/master' do |f| %>
  <div class="application">
    <%= yield %>
  </div>
<% end %>

app/views/layouts/fullscreen_panel.html.erb
<%= render layout: 'layouts/master' do |f| %>
  <%= render partial: 'shared/navbar' %>
  <div class="panel__wrapper">
    <%= render layout: 'layouts/panel' do %>
      <%= yield %>
    <% end %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= render partial: 'shared/navbar' %>

<div class="notes" data-stimulus-controller="notes">
  <div class="notes__editor">
    <div class="note"
      data-stimulus-action="input->notes#onChanged"
      data-stimulus-target="notes.note">
      <%= @note.text.html_safe %>
    </div>

    <!-- Shadow form -->
    <div class="note__shadow-form">
      <%= form_with scope: :note,
        url: note_path,
        method: :patch,
        data: {
          stimulus_action:
            'ajax:send->notes#onSend ajax:success->notes#onSuccess ajax:error->notes#onError'
        } do |form| %>
        <div class="form__group">
          <%= form.text_area :text,
            class: 'form__input',
            data: { stimulus_target: 'notes.input' } %>
        </div>
        <%= form.submit class: 'button', data: { stimulus_target: 'notes.submitButton' } %>
      <% end %>
    </div>
  </div>

  <div class="navbar navbar--bottom">
    <section class="navbar__section">
      <span class="navbar__label" data-stimulus-target="notes.statusLabel">
        <%= t('.saved') %>
      </span>
    </section>
  </div>
</div>

app/views/notes/index.html.erb
<!-- Uses page-wide notes controller -->
<% content_for :toolbar do %>
  <%= button_tag t('.save'),
    class: ['btn', 'btn-primary'], data: { action: 'click->notes#save' } %>
<% end %>

<div class="note-content">
  <div class="note-editor" contenteditable="true" data-target="notes.note">
    <!-- TODO: Use HTML sanitizer instead for security reasons -->
    <%= @note.text.html_safe %>
  </div>

  <!-- Shadow form -->
  <div class="d-hide">
    <%= form_with scope: :note, url: notes_update_path do |form| %>
      <div class="form-group">
        <%= form.text_area :text, class: 'form-input', data: { target: 'notes.input' } %>
      </div>
      <%= form.submit class: ['btn', 'btn-success'], data: { target: 'notes.submit' } %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="navbar">
  <section class="navbar__section navbar__section--left">
    <%= link_to t('name'), home_index_path, class: 'navbar__brand' %>
  </section>

  <section class="navbar__section navbar__section--right">
    <% if signed_in? %>
      <%= navbar_link_to t('.edit'),
        edit_note_path,
        class: 'navbar__link' %>
      <%= navbar_link_to current_user.email,
        edit_user_path,
        class: 'navbar__link' %>
      <%= button_to t('shared.navbar.sign_out'),
        sign_out_path,
        method: :delete, class: 'navbar__link' %>
    <% else %>
      <%= navbar_link_to t('shared.navbar.sign_up'),
        sign_up_path,
        class: 'navbar__link' %>
      <%= navbar_link_to t('shared.navbar.sign_in'),
        sign_in_path,
        class: 'navbar__link' %>
    <% end %>
  </section>
</header>

app/views/shared/_notifications.html.erb
<% unless flash.empty? %>
  <div class="notification__wrapper"
    data-stimulus-controller="notifications">
    <% flash.each do |key, value| %>
      <div class="notification notification--<%= key %> notification--interactive"
        data-stimulus-action="click->notifications#close">
        <%= value %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%# Email %>
<div class="form__group">
  <%= form.label :email, class: 'form__label' %>
  <%= form.text_field :email,
    type: 'email',
    class: 'form__input',
    autofocus: true,
    placeholder: 'joe@example.com' %>
</div>

<%# Password %>
<div class="form__group">
  <%= form.label :password, class: 'form__label' %>
  <%= form.password_field :password,
    class: 'form__input',
    placeholder: '••••••••••',
    data: {
      stimulus_action: 'input->users#onPasswordInput',
      stimulus_target: 'users.passwordField'
    } %>
</div>

app/views/users/_new.html.erb
<% content_for :header do %>
  <%= t('.title') %>
<% end %>

<% content_for :navigation do %>
  <nav class="navbar navbar--inline">
    <%= link_to t('shared.navbar.sign_up'),
      sign_up_path,
      class: ['navbar__link', 'active'] %>
    <%= link_to t('shared.navbar.sign_in'),
      sign_in_path,
      class: 'navbar__link' %>
  </nav>
<% end %>

<% content_for :body do %>
  <% if Clearance.configuration.allow_sign_up? %>
    <%= form_for @user do |form| %>
      <%= render partial: 'users/form', object: form %>

      <div class="form__submit">
        <%= form.submit class: ['button', 'button--primary'] %>
      </div>
    <% end %>
  <% else %>
    <div class="notification__wrapper">
      <div class="notification notification--notice">
        <%= t('.sign_up_disabled') %>
      </div>
    </div>
  <% end %>
<% end %>

<% content_for :footer do %>
  <% link_to t('.cancel'), home_index_path %>
<% end %>

app/views/users/edit.html.erb
<% content_for :header do %>
  <%= t('.title') %>
<% end %>

<% content_for :body do %>
  <%= render partial: 'shared/notifications' %>
  <%= form_for @user, data: { stimulus_controller: 'users' } do |form| %>
    <%= render partial: 'users/form', object: form %>

    <%# Additional password confirmation field %>
    <div class="form__group">
      <%= form.label :password_confirmation, class: 'form__label' %>
      <%= form.password_field :password_confirmation,
        class: 'form__input',
        placeholder: '••••••••••',
        data: {
          stimulus_action: 'input->users#onPasswordInput',
          stimulus_target: 'users.passwordConfirmationField'
        } %>
    </div>

    <div class="form__submit">
      <%= form.submit class: ['button', 'button--primary'],
        data: { stimulus_target: 'users.submitButton' } %>
    </div>
  <% end %>
<% end %>

<% content_for :footer do %>
  <% link_to t('.cancel'), home_index_path %>
<% end %>

app/views/users/new.html.erb
<%= render partial: 'users/new' %>